- lib/components/dropdown/dropdown.tsx
- package.json
Fixes https://github.com/GrindrodBank/spoon-ui/issues/3
> 1141 triangle under combobox fix

- lib/components/dropdown/dropdown.tsx
- package.json
- yarn.lock
Addresses https://github.com/GrindrodBank/spoon-ui/issues/4
> 1142 axios cve 2019 10742

- app/modules/navigation/navigation.tsx
- app/modules/selection/selection.tsx
- lib/components/progression/progression-item.tsx
- lib/components/progression/progression.scss
- lib/components/progression/progression.tsx
- lib/components/selection/radio-button-value.ts
- lib/components/selection/radiogroup.tsx
- package.json
https://redmine.bigbaobab.org/issues/1213
Has customizable icons
> 1213 vertical progress item

- app/modules/dropdowns/dropdown.tsx
- app/modules/forms/forms.tsx
- app/modules/navigation/navigation.tsx
- app/modules/selection/selection.tsx
- i18n/de/colors.json
- i18n/en/colors.json
- lib/_bootstrap-variables.scss
- lib/components/add-to-from-list/add-to-from-list.tsx
- lib/components/color-theme-editor/color-theme-editor.tsx
- lib/components/context-menu/context-menu.tsx
- lib/components/dropdown/dropdown-item.tsx
- lib/components/dropdown/dropdown.tsx
- lib/components/dropdown/text-translation-and-value.ts
- lib/components/items-per-page/items-per-page.tsx
- lib/components/selection/radiogroup.tsx
- lib/components/selection/selection.scss
- lib/components/tag-input/tag-input.tsx
- lib/spoon-ui.scss
- package.json
Also generics for the dropdown menu value
With the background color also as a variable
> Horizontal radio buttons

- lib/components/selection/radiogroup.tsx
- lib/components/selection/selection.scss
- package.json
1243 Fix horizontal radio display issues when inside a form
> 1243 Fix horizontal radio display issues when inside a form

- Dockerfile
- package.json
Changed build image to 'alpine' to address security alerts in Xray
> update build image to alpine

- lib/components/dropdown/dropdown-item.tsx
- lib/components/dropdown/dropdown.tsx
- lib/components/forms/combobox-input.tsx
- lib/components/forms/form-input.tsx
- lib/components/index.ts
- lib/validation/index.ts
- lib/validation/required.ts
- package.json
- test/javascript/spec/lib/required.spec.tsx
- yarn.lock
> 1423 combobox input fixes

- lib/components/dropdown/dropdown.tsx
- lib/components/forms/combobox-input.tsx
- lib/validation/required.ts
- package.json
Fixed a bug that the form is not marked dirty when closing
> 1243 combobox marked dirty on close

- app/modules/forms/forms.tsx
- i18n/de/forms.json
- i18n/en/forms.json
- lib/components/forms/form-input.tsx
- lib/components/selection/radiobutton.tsx
- lib/components/selection/radiogroup.tsx
- lib/util/translation.ts
- lib/validation/validate.ts
- package.json
Radio buttons' text weren't translated do to override of radio group name
NPE fix on combobox & radio input when no validators are defined
> 1243 radio button translation fix and validator npe

- app/modules/forms/forms.tsx
- package.json
> 1243 npe on combobox unselect

- app/modules/forms/forms.tsx
- i18n/de/forms.json
- i18n/en/forms.json
- lib/components/dropdown/dropdown.tsx
- package.json
The combobox's placeholder was not translated.
No it is.
> 1243 comboinput placeholder translated

- lib/components/dropdown/dropdown.tsx
- lib/components/forms/multiple-selection-input.tsx
- package.json
Fix for type issue from https://build.bigbaobab.org/blue/organizations/jenkins/ocs-ui/detail/1243-merge-main-scaffolding/1/pipeline
> Fix class extension on multiple select

- app/modules/forms/forms.tsx
- lib/components/forms/combobox-input.tsx
- lib/components/forms/form-input.tsx
- lib/components/forms/multiple-selection-input.tsx
- lib/components/forms/radio-input.tsx
- lib/components/forms/text-input.tsx
- lib/components/selection/radiogroup.tsx
- package.json
Have a property to disable form inputs
> 1495 disabled inputs

- app/modules/dropdowns/dropdown.tsx
- app/modules/forms/forms.tsx
- lib/_bootstrap-variables.scss
- lib/components/button/button.scss
- lib/components/button/button.tsx
- lib/components/calendar-input/calendar-input.scss
- lib/components/calendar-input/calendar-input.tsx
- lib/components/context-menu/context-menu.tsx
- lib/components/dropdown-search-bar/dropdown-search-bar.tsx
- lib/components/dropdown/dropdown-item.scss
- lib/components/dropdown/dropdown-item.tsx
- lib/components/dropdown/dropdown-tag.scss
- lib/components/dropdown/dropdown-tag.tsx
- lib/components/dropdown/dropdown.scss
- lib/components/dropdown/dropdown.tsx
- lib/components/expandable/expandable.tsx
- lib/components/opener/opener.scss
- lib/components/opener/opener.tsx
- lib/components/search-bar/search-bar.scss
- lib/components/search-bar/search-bar.tsx
- lib/components/selection/checkbox.tsx
- lib/components/selection/radiobutton.tsx
- lib/components/selection/selection.scss
- lib/components/tag-input/tag-input.tsx
- lib/components/with-popover/with-popover.tsx
- lib/spoon-ui.scss
- lib/util/dirty-input.ts
- package.json
> bug fix for initial value of dropdown

- app/modules/containers/containers.tsx
- app/modules/forms/forms.tsx
- app/modules/navigation/navigation.tsx
- app/modules/selection/selection.tsx
- lib/_bootstrap-variables.scss
- lib/components/add-to-from-list/add-to-from-list.tsx
- lib/components/context-menu/context-menu.scss
- lib/components/context-menu/context-menu.tsx
- lib/components/dropdown-search-bar/dropdown-search-bar.tsx
- lib/components/dropdown/dropdown-item.scss
- lib/components/dropdown/dropdown-tag.scss
- lib/components/dropdown/dropdown.scss
- lib/components/dropdown/dropdown.tsx
- lib/components/items-per-page/items-per-page.scss
- lib/components/search-bar/search-bar.tsx
- lib/components/selection/checkbox.tsx
- lib/components/selection/radiobutton.tsx
- lib/components/selection/radiogroup.tsx
- lib/components/selection/toggle.tsx
- lib/components/simple-menu/simple-menu.scss
- lib/components/tag-input/tag-input.scss
- lib/components/tag-input/tag-input.tsx
- lib/components/with-popover/with-popover.tsx
- lib/spoon-ui.scss
- package.json
In the scope of this PR:
- Make sure all components can be controlled by parent
- Unify props shape on all components
- Make sure all components can override styles
- Bug fix for initial value of dropdown
Additionally:
- context menu is rebuilt to use simple menu + withPopover
- tag input uses withPopover + grid
> 1951,1952,1953,1955

- Dockerfile
- app/modules/buttons/buttons.tsx
- lib/_bootstrap-variables.scss
- lib/components/button/button.scss
- lib/components/dropdown/dropdown.scss
- lib/components/opener/opener.scss
- lib/spoon-ui.scss
- package.json
> 2468 ui  implement bank branding

- app/modules/navigation/navigation.tsx
- lib/_bootstrap-variables.scss
- lib/components/accordion-header/accordion-header.scss
- lib/components/accordion-header/accordion-header.tsx
- lib/components/index.ts
- lib/components/sidemenu/sidemenu.scss
- lib/components/sidemenu/sidemenuitem.scss
- lib/spoon-ui.scss
- package.json
> Fix defects

- lib/components/accordion-header/accordion-header.scss
- lib/components/accordion-header/accordion-header.tsx
- lib/components/info-card/info-card.scss
- package.json
> restyle accordion header

- app/modules/navigation/navigation.tsx
- lib/_bootstrap-variables.scss
- lib/components/accordion-header/accordion-header.scss
- lib/components/dropdown/dropdown-item.scss
- lib/components/progression/progression-item.tsx
- lib/components/progression/progression.scss
- lib/components/sidemenu/sidemenu.scss
- lib/spoon-ui.scss
- package.json
> restyled progression bar

- app/modules/forms/forms.tsx
- html/index.html
- lib/components/forms/text-input.tsx
- lib/components/progression/progression-item.tsx
- lib/components/progression/progression.scss
- lib/components/sidemenu/sidemenu.scss
- lib/components/sidemenu/sidemenuitem.scss
- package.json
> add line to progression bar

- app/modules/forms/forms.tsx
- lib/components/forms/form-input.scss
- lib/components/search-bar/search-bar.scss
- lib/components/search-bar/search-bar.tsx
- lib/components/sidemenu/sidemenu.scss
- lib/components/sidemenu/sidemenuitem.scss
- lib/spoon-ui.scss
- package.json
> create global Search
